//
// ActionField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Is the action taken by a user in a workflow on this step.  &#x60;0 &#x3D; SignDocument 1 &#x3D; ViewDocument 2 &#x3D; ApproveDocument&#x60;  */
public enum ActionField: Int, Codable, CaseIterable {
    case SignDocument = 0
    case ViewDocument = 1
    case ApproveDocument = 2
}
