//
// AddWorkflowStepV2Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Add a step to the Workflow request. */
public struct AddWorkflowStepV2Request: Codable {

    public var actionField: ActionField
    /** Mobile number of participant */
    public var cellField: String
    /** Document ID field. */
    public var docIDField: String
    /** Participant email address. */
    public var emailField: String
    /** Participant firstname. */
    public var firstNameField: String
    /** Participant 2 Digit ISO Language Code &#x60;en &#x3D; English es &#x3D; Spanish fr &#x3D; French ect&#x60; */
    public var languageCodeField: String
    /** Participant last name. */
    public var lastNameField: String
    public var proxyAllowedField: ProxyAllowedField
    public var tokenField: TokenField

    public init(actionField: ActionField, cellField: String, docIDField: String, emailField: String, firstNameField: String, languageCodeField: String, lastNameField: String, proxyAllowedField: ProxyAllowedField, tokenField: TokenField) {
        self.actionField = actionField
        self.cellField = cellField
        self.docIDField = docIDField
        self.emailField = emailField
        self.firstNameField = firstNameField
        self.languageCodeField = languageCodeField
        self.lastNameField = lastNameField
        self.proxyAllowedField = proxyAllowedField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionField = "ActionField"
        case cellField = "CellField"
        case docIDField = "DocIDField"
        case emailField = "EmailField"
        case firstNameField = "FirstNameField"
        case languageCodeField = "LanguageCodeField"
        case lastNameField = "LastNameField"
        case proxyAllowedField = "ProxyAllowedField"
        case tokenField = "TokenField"
    }

}
