//
// AddWokflowStepV2Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Add a step to a Workflow response. */
public struct AddWokflowStepV2Response: Codable {

    /** Document ID field. */
    public var docIDField: Double
    /** Document flow ID field */
    public var flowIDField: Double
    public var flowStepsField: Set<AddWokflowStepV2ResponseFlowStepsField>
    /** Displays the result of the call. */
    public var resultField: String

    public init(docIDField: Double, flowIDField: Double, flowStepsField: Set<AddWokflowStepV2ResponseFlowStepsField>, resultField: String) {
        self.docIDField = docIDField
        self.flowIDField = flowIDField
        self.flowStepsField = flowStepsField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case flowIDField = "FlowIDField"
        case flowStepsField = "FlowStepsField"
        case resultField = "ResultField"
    }

}
