//
// AddWokflowStepV2ResponseFlowStepsField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddWokflowStepV2ResponseFlowStepsField: Codable {

    public var actionField: ActionField
    /** Participant email address field. */
    public var emailField: String
    /** Document Flow ID field. */
    public var flowIDField: Double

    public init(actionField: ActionField, emailField: String, flowIDField: Double) {
        self.actionField = actionField
        self.emailField = emailField
        self.flowIDField = flowIDField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionField = "ActionField"
        case emailField = "EmailField"
        case flowIDField = "FlowIDField"
    }

}
