//
// AdvancedFieldType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Document Prepper Advanced Field Types  &#x60; 0 &#x3D; DropDown 1 &#x3D; CheckBoxGroup 2 &#x3D; OptionalDropDown 3 &#x3D; RadioGroup 4 &#x3D; DateMand 5 &#x3D; DateOpt 6 &#x3D; DropDownCountry 7 &#x3D; OptionalDropDownCountry 8 &#x3D; DropDownMobilePrefix 9 &#x3D; OptionalDropDownMobilePrefix &#x60; */
public enum AdvancedFieldType: Double, Codable, CaseIterable {
    case DropDown = 0
    case CheckBoxGroup = 1
    case OptionalDropDown = 2
    case RadioGroup = 3
    case DateMand = 4
    case DateOpt = 5
    case DropDownCountry = 6
    case OptionalDropDownCountry = 7
    case DropDownMobilePrefix = 8
    case OptionalDropDownMobilePrefix = 9
}
