//
// ApplyPrepperTemplateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Used to get the response afetr applying a template. */
public struct ApplyPrepperTemplateResponse: Codable {

    /** Displays the result of the call. */
    public var resultField: String

    public init(resultField: String) {
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resultField = "ResultField"
    }

}
