//
// ApplyPrepperTemplateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Used to send a request for applying a template. */
public struct ApplyPrepperTemplateRequest: Codable {

    /** Document ID field. */
    public var docIDField: Double
    /** Document prepper template ID field. */
    public var prepperTemplateIDField: Double
    public var tokenField: TokenField

    public init(docIDField: Double, prepperTemplateIDField: Double, tokenField: TokenField) {
        self.docIDField = docIDField
        self.prepperTemplateIDField = prepperTemplateIDField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case prepperTemplateIDField = "PrepperTemplateIDField"
        case tokenField = "TokenField"
    }

}
