//
// AutoExpire.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Sets an Auto Expire that will expire the document if not completed by the Due Date.  &#x60;0 &#x3D; No 1 &#x3D; Yes&#x60;  */
public enum AutoExpire: Int, Codable, CaseIterable {
    case No = 0
    case Yes = 1
}
