//
// AutoRemind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Sets an Auto Reminder email to go out daily to workflow participants that have not signed the document.  &#x60;0 &#x3D; No 1 &#x3D; Yes&#x60; */
public enum AutoRemind: Int, Codable, CaseIterable {
    case No = 0
    case Yes = 1
}
