//
// CancelFlowResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when a user cancelled a workflow. */
public struct CancelFlowResponse: Codable {

    /** Document ID field. */
    public var docIDField: Double
    /** Displays the result of the call. */
    public var resultField: String

    public init(docIDField: Double, resultField: String) {
        self.docIDField = docIDField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case resultField = "ResultField"
    }

}
