//
// CreatePortfolioRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Used to create a portfolio. */
public struct CreatePortfolioRequest: Codable {

    /** Document ID field. */
    public var docIDField: Double
    /** Portfolio name displayed in SigniFlow */
    public var portfolioNameField: String
    public var tokenIDField: TokenField

    public init(docIDField: Double, portfolioNameField: String, tokenIDField: TokenField) {
        self.docIDField = docIDField
        self.portfolioNameField = portfolioNameField
        self.tokenIDField = tokenIDField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case portfolioNameField = "PortfolioNameField"
        case tokenIDField = "TokenIDField"
    }

}
