//
// CreatePortfolioResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response received after a portfolio is created. */
public struct CreatePortfolioResponse: Codable {

    /** Document portfolio ID field. */
    public var portfolioIDField: Double
    /** Displays the result of the call. */
    public var resultField: String

    public init(portfolioIDField: Double, resultField: String) {
        self.portfolioIDField = portfolioIDField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case portfolioIDField = "PortfolioIDField"
        case resultField = "ResultField"
    }

}
