//
// CreateWorkflowResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when creating a document workflow. */
public struct CreateWorkflowResponse: Codable {

    /** Document Id created in SigniFlow */
    public var docIDField: Int
    /** Displays the result of the call. */
    public var resultField: String

    public init(docIDField: Int, resultField: String) {
        self.docIDField = docIDField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case resultField = "ResultField"
    }

}
