//
// DeleteDocResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response that will be returned when a document is deleted. */
public struct DeleteDocResponse: Codable {

    /** Displays the result of the call. */
    public var resultField: String

    public init(resultField: String) {
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resultField = "ResultField"
    }

}
