//
// DocExtension.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Document Extension   &#x60; 0 &#x3D; pdf 1 &#x3D; xls 2 &#x3D; txt 3 &#x3D; xlsx 4 &#x3D; docx 5 &#x3D; doc 6 &#x3D; xml 7 &#x3D; png 8 &#x3D; jpg 9 &#x3D; gif &#x60;  */
public enum DocExtension: Int, Codable, CaseIterable {
    case pdf = 0
    case xls = 1
    case txt = 2
    case xlsx = 3
    case docx = 4
    case doc = 5
    case xml = 6
    case png = 7
    case jpg = 8
    case gif = 9
}
