//
// DocPrepperAddFieldsFlowIDRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent when fields are added to a document using a FlowID. */
public struct DocPrepperAddFieldsFlowIDRequest: Codable {

    public var docFieldTypeField: FieldType
    /** Document ID. */
    public var docIDField: Double
    /** Document Flow ID. */
    public var flowIDField: Double
    /** Field height. */
    public var heightField: String
    /** Field width. */
    public var widthField: String
    /** Is the field invisible. */
    public var isInvisibleField: Bool
    /** Document link. */
    public var linkToField: String
    /** Field page number. */
    public var pageNumberField: Double
    /** Field name field. */
    public var nameField: String
    /** User email address field. */
    public var userEmailField: String
    /** Document field x-coordinates. */
    public var xCoordinateField: String
    /** Document field y-coordinates. */
    public var yCoordinateField: String
    public var tokenField: TokenField

    public init(docFieldTypeField: FieldType, docIDField: Double, flowIDField: Double, heightField: String, widthField: String, isInvisibleField: Bool, linkToField: String, pageNumberField: Double, nameField: String, userEmailField: String, xCoordinateField: String, yCoordinateField: String, tokenField: TokenField) {
        self.docFieldTypeField = docFieldTypeField
        self.docIDField = docIDField
        self.flowIDField = flowIDField
        self.heightField = heightField
        self.widthField = widthField
        self.isInvisibleField = isInvisibleField
        self.linkToField = linkToField
        self.pageNumberField = pageNumberField
        self.nameField = nameField
        self.userEmailField = userEmailField
        self.xCoordinateField = xCoordinateField
        self.yCoordinateField = yCoordinateField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docFieldTypeField = "DocFieldTypeField"
        case docIDField = "DocIDField"
        case flowIDField = "FlowIDField"
        case heightField = "HeightField"
        case widthField = "WidthField"
        case isInvisibleField = "IsInvisibleField"
        case linkToField = "LinkToField"
        case pageNumberField = "PageNumberField"
        case nameField = "NameField"
        case userEmailField = "UserEmailField"
        case xCoordinateField = "XCoordinateField"
        case yCoordinateField = "YCoordinateField"
        case tokenField = "TokenField"
    }

}
