//
// DocPrepperAddAdvancedFieldsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response when adding advanced fields to a document. */
public struct DocPrepperAddAdvancedFieldsResponse: Codable {

    public var advancedFieldResponseListField: Set<DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField>
    /** Displays the result of the call. */
    public var resultField: String

    public init(advancedFieldResponseListField: Set<DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField>, resultField: String) {
        self.advancedFieldResponseListField = advancedFieldResponseListField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case advancedFieldResponseListField = "AdvancedFieldResponseListField"
        case resultField = "ResultField"
    }

}
