//
// DocPrepperAddFieldsFlowIDResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response retuenrd when fields are added to a document using a FlowID. */
public struct DocPrepperAddFieldsFlowIDResponse: Codable {

    /** Document ID. */
    public var docIDField: Double
    public var fieldTypeField: FieldType
    /** The height of the field. */
    public var heightField: String
    /** Field page number. */
    public var pageNumberField: Double
    /** Document prepper field ID. */
    public var prepperFieldIDField: Double
    /** Displays the result of the call. */
    public var resultField: String
    /** SigniFlow User ID */
    public var userIDField: Double
    /** The width of the field. */
    public var widthField: String
    /** X-coordinates of the field. */
    public var xCoordinateField: String
    /** Y-coordinates of the field. */
    public var yCoordinateField: String

    public init(docIDField: Double, fieldTypeField: FieldType, heightField: String, pageNumberField: Double, prepperFieldIDField: Double, resultField: String, userIDField: Double, widthField: String, xCoordinateField: String, yCoordinateField: String) {
        self.docIDField = docIDField
        self.fieldTypeField = fieldTypeField
        self.heightField = heightField
        self.pageNumberField = pageNumberField
        self.prepperFieldIDField = prepperFieldIDField
        self.resultField = resultField
        self.userIDField = userIDField
        self.widthField = widthField
        self.xCoordinateField = xCoordinateField
        self.yCoordinateField = yCoordinateField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case fieldTypeField = "FieldTypeField"
        case heightField = "HeightField"
        case pageNumberField = "PageNumberField"
        case prepperFieldIDField = "PrepperFieldIDField"
        case resultField = "ResultField"
        case userIDField = "UserIDField"
        case widthField = "WidthField"
        case xCoordinateField = "XCoordinateField"
        case yCoordinateField = "YCoordinateField"
    }

}
