//
// DownloadPortfolioResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when a user wants to download a portfolio. */
public struct DownloadPortfolioResponse: Codable {

    /** Portfolio data field. */
    public var portfolioDataField: String
    /** Portfolio ID. */
    public var portfolioIDField: Double
    /** Portfolio name. */
    public var portfolioNameField: String
    /** Displays the result of the call. */
    public var resultField: String

    public init(portfolioDataField: String, portfolioIDField: Double, portfolioNameField: String, resultField: String) {
        self.portfolioDataField = portfolioDataField
        self.portfolioIDField = portfolioIDField
        self.portfolioNameField = portfolioNameField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case portfolioDataField = "PortfolioDataField"
        case portfolioIDField = "PortfolioIDField"
        case portfolioNameField = "PortfolioNameField"
        case resultField = "ResultField"
    }

}
