//
// FullWorkflowRequestWorkflowUsersListField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FullWorkflowRequestWorkflowUsersListField: Codable {

    /** Refers to the order of signatures from the users. */
    public var actionField: Double
    /** Allow proxy confirmation field. */
    public var allowProxyField: Double
    /** ### Enable auto sign.  &#x60;True &#x3D; Signature will be applied automaticly False &#x3D; User will need to login and Sign&#x60;  */
    public var autoSignField: Bool
    /** Workflow user&#39;s email addresses. */
    public var emailAddressField: String
    public var groupStepField: FullWorkflowRequestGroupStepField?
    /** #### Sets the display language for the user ##### ISO 2 Digit Code  &#x60;en &#x3D; English es &#x3D; Spanish fr &#x3D; French&#x60;  */
    public var languageCodeField: String
    /** Location latitude. */
    public var latitudeField: String
    /** Location longtitude. */
    public var longitudeField: String
    /** Group user&#39;s mobile number. */
    public var mobileNumberField: String
    /** Preloaded user&#39;s who will be using the face to face signature field. */
    public var preloadedFaceToFaceSignersField: Set<Any>?
    /** Reason for signature. */
    public var signReasonField: String
    /** Face to face user&#39;s password. */
    public var signerPasswordField: String
    /** Face to face user&#39;s first name. */
    public var userFirstNameField: String
    /** Face to face user&#39;s full name. */
    public var userFullNameField: String
    /** Face to face user&#39;s last name. */
    public var userLastNameField: String
    /** The list of the workflowed documents field. */
    public var workflowUserFieldsField: Set<FullWorkflowRequestWorkflowUserFieldsField>?

    public init(actionField: Double, allowProxyField: Double, autoSignField: Bool, emailAddressField: String, groupStepField: FullWorkflowRequestGroupStepField? = nil, languageCodeField: String, latitudeField: String, longitudeField: String, mobileNumberField: String, preloadedFaceToFaceSignersField: Set<Any>? = nil, signReasonField: String, signerPasswordField: String, userFirstNameField: String, userFullNameField: String, userLastNameField: String, workflowUserFieldsField: Set<FullWorkflowRequestWorkflowUserFieldsField>? = nil) {
        self.actionField = actionField
        self.allowProxyField = allowProxyField
        self.autoSignField = autoSignField
        self.emailAddressField = emailAddressField
        self.groupStepField = groupStepField
        self.languageCodeField = languageCodeField
        self.latitudeField = latitudeField
        self.longitudeField = longitudeField
        self.mobileNumberField = mobileNumberField
        self.preloadedFaceToFaceSignersField = preloadedFaceToFaceSignersField
        self.signReasonField = signReasonField
        self.signerPasswordField = signerPasswordField
        self.userFirstNameField = userFirstNameField
        self.userFullNameField = userFullNameField
        self.userLastNameField = userLastNameField
        self.workflowUserFieldsField = workflowUserFieldsField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionField = "ActionField"
        case allowProxyField = "AllowProxyField"
        case autoSignField = "AutoSignField"
        case emailAddressField = "EmailAddressField"
        case groupStepField = "GroupStepField"
        case languageCodeField = "LanguageCodeField"
        case latitudeField = "LatitudeField"
        case longitudeField = "LongitudeField"
        case mobileNumberField = "MobileNumberField"
        case preloadedFaceToFaceSignersField = "PreloadedFaceToFaceSignersField"
        case signReasonField = "SignReasonField"
        case signerPasswordField = "SignerPasswordField"
        case userFirstNameField = "UserFirstNameField"
        case userFullNameField = "UserFullNameField"
        case userLastNameField = "UserLastNameField"
        case workflowUserFieldsField = "WorkflowUserFieldsField"
    }

}
