//
// FullWorkflowRequestPortfolioInformationField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Portfolio information. */
public struct FullWorkflowRequestPortfolioInformationField: Codable {

    /** Create portfolio. */
    public var createPortfolioField: Bool
    /** Portfolio link. */
    public var linkToPortfolioField: Bool
    /** Portfolio ID. */
    public var portfolioIDField: Double
    /** Portfolio name. */
    public var portfolioNameField: String

    public init(createPortfolioField: Bool, linkToPortfolioField: Bool, portfolioIDField: Double, portfolioNameField: String) {
        self.createPortfolioField = createPortfolioField
        self.linkToPortfolioField = linkToPortfolioField
        self.portfolioIDField = portfolioIDField
        self.portfolioNameField = portfolioNameField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createPortfolioField = "CreatePortfolioField"
        case linkToPortfolioField = "LinkToPortfolioField"
        case portfolioIDField = "PortfolioIDField"
        case portfolioNameField = "PortfolioNameField"
    }

}
