//
// FullWorkflowRequestGroupStepFieldGroupMembersField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FullWorkflowRequestGroupStepFieldGroupMembersField: Codable {

    public var languageCodeField: String
    public var userEmailField: String
    public var userFullNameField: String
    public var userMobileNumberField: String

    public init(languageCodeField: String, userEmailField: String, userFullNameField: String, userMobileNumberField: String) {
        self.languageCodeField = languageCodeField
        self.userEmailField = userEmailField
        self.userFullNameField = userFullNameField
        self.userMobileNumberField = userMobileNumberField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case languageCodeField = "LanguageCodeField"
        case userEmailField = "UserEmailField"
        case userFullNameField = "UserFullNameField"
        case userMobileNumberField = "UserMobileNumberField"
    }

}
