//
// FullWorkflowResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned on FullWorkflow. */
public struct FullWorkflowResponse: Codable {

    public var docField: String
    public var docIDField: Double
    public var portfolioIDField: Double
    /** Displays the result of the call. */
    public var resultField: String
    public var statusField: String

    public init(docField: String, docIDField: Double, portfolioIDField: Double, resultField: String, statusField: String) {
        self.docField = docField
        self.docIDField = docIDField
        self.portfolioIDField = portfolioIDField
        self.resultField = resultField
        self.statusField = statusField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docField = "DocField"
        case docIDField = "DocIDField"
        case portfolioIDField = "PortfolioIDField"
        case resultField = "ResultField"
        case statusField = "StatusField"
    }

}
