//
// FullWorkflowRequestWorkflowUserFieldsField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FullWorkflowRequestWorkflowUserFieldsField: Codable {

    /** Field type. */
    public var fieldTypeField: Double
    /** The font family of the fields text. */
    public var fontFamilyField: String
    /** The font size of the fields text. */
    public var fontSizeField: Double
    /** The users in the group&#39;s user number. */
    public var groupUserNumberField: Double
    /** Field height. */
    public var heightField: String
    /** Is the field visible. */
    public var isInvisibleField: Bool
    /** Field page number. */
    public var pageNumberField: Double
    /** Field tag name. */
    public var tagNameField: String
    /** Field value. */
    public var valueField: String
    /** Field width. */
    public var widthField: String
    /** The fields x-coordinates. */
    public var xCoordinateField: String
    /** The fields x-coordinates offset. */
    public var xOffsetField: Double
    /** The fields y-coordinates. */
    public var yCoordinateField: String
    /** The fields y-coordinates offset. */
    public var yOffsetField: Double

    public init(fieldTypeField: Double, fontFamilyField: String, fontSizeField: Double, groupUserNumberField: Double, heightField: String, isInvisibleField: Bool, pageNumberField: Double, tagNameField: String, valueField: String, widthField: String, xCoordinateField: String, xOffsetField: Double, yCoordinateField: String, yOffsetField: Double) {
        self.fieldTypeField = fieldTypeField
        self.fontFamilyField = fontFamilyField
        self.fontSizeField = fontSizeField
        self.groupUserNumberField = groupUserNumberField
        self.heightField = heightField
        self.isInvisibleField = isInvisibleField
        self.pageNumberField = pageNumberField
        self.tagNameField = tagNameField
        self.valueField = valueField
        self.widthField = widthField
        self.xCoordinateField = xCoordinateField
        self.xOffsetField = xOffsetField
        self.yCoordinateField = yCoordinateField
        self.yOffsetField = yOffsetField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fieldTypeField = "FieldTypeField"
        case fontFamilyField = "FontFamilyField"
        case fontSizeField = "FontSizeField"
        case groupUserNumberField = "GroupUserNumberField"
        case heightField = "HeightField"
        case isInvisibleField = "IsInvisibleField"
        case pageNumberField = "PageNumberField"
        case tagNameField = "TagNameField"
        case valueField = "ValueField"
        case widthField = "WidthField"
        case xCoordinateField = "XCoordinateField"
        case xOffsetField = "XOffsetField"
        case yCoordinateField = "YCoordinateField"
        case yOffsetField = "YOffsetField"
    }

}
