//
// FullWorkflowRequestGroupStepField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Steps of the group signers in the workflow. */
public struct FullWorkflowRequestGroupStepField: Codable {

    /** The list of users in a group in the workflow. */
    public var groupMembersField: Set<FullWorkflowRequestGroupStepFieldGroupMembersField>
    /** Group name. */
    public var groupNameField: String
    /** Required number of signatures in the group. */
    public var requiredNumberOfSignaturesField: Double

    public init(groupMembersField: Set<FullWorkflowRequestGroupStepFieldGroupMembersField>, groupNameField: String, requiredNumberOfSignaturesField: Double) {
        self.groupMembersField = groupMembersField
        self.groupNameField = groupNameField
        self.requiredNumberOfSignaturesField = requiredNumberOfSignaturesField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupMembersField = "GroupMembersField"
        case groupNameField = "GroupNameField"
        case requiredNumberOfSignaturesField = "RequiredNumberOfSignaturesField"
    }

}
