//
// FullWorkflowRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Request a fullworkflow of a document. */
public struct FullWorkflowRequest: Codable {

    /** Additional data. */
    public var additionalDataField: String
    public var autoRemindField: AutoRemind
    /** Custom message. */
    public var customMessageField: String
    /** Document field. */
    public var docField: String
    /** Document name. */
    public var docNameField: String
    /** Document due date. */
    public var dueDateField: String
    public var extensionField: DocExtension
    /** Flatten document. */
    public var flattenDocumentField: Bool
    /** Keep content security. */
    public var keepContentSecurityField: Bool
    /** Keep custom properties. */
    public var keepCustomPropertiesField: Bool
    /** Keep XMP meta data. */
    public var keepXMPMetadataField: Bool
    public var portfolioInformationField: FullWorkflowRequestPortfolioInformationField
    /** Document priority. */
    public var priorityField: Double
    /** SLA */
    public var sLAField: Double
    /** Confirm first user email notification will or will not be sent. */
    public var sendFirstEmailField: Bool
    /** Confirm that workflow emails will or will not be sent. */
    public var sendWorkflowEmailsField: Bool
    public var tokenField: TokenField
    /** List of users in the workflow. */
    public var workflowUsersListField: Set<FullWorkflowRequestWorkflowUsersListField>

    public init(additionalDataField: String, autoRemindField: AutoRemind, customMessageField: String, docField: String, docNameField: String, dueDateField: String, extensionField: DocExtension, flattenDocumentField: Bool, keepContentSecurityField: Bool, keepCustomPropertiesField: Bool, keepXMPMetadataField: Bool, portfolioInformationField: FullWorkflowRequestPortfolioInformationField, priorityField: Double, sLAField: Double, sendFirstEmailField: Bool, sendWorkflowEmailsField: Bool, tokenField: TokenField, workflowUsersListField: Set<FullWorkflowRequestWorkflowUsersListField>) {
        self.additionalDataField = additionalDataField
        self.autoRemindField = autoRemindField
        self.customMessageField = customMessageField
        self.docField = docField
        self.docNameField = docNameField
        self.dueDateField = dueDateField
        self.extensionField = extensionField
        self.flattenDocumentField = flattenDocumentField
        self.keepContentSecurityField = keepContentSecurityField
        self.keepCustomPropertiesField = keepCustomPropertiesField
        self.keepXMPMetadataField = keepXMPMetadataField
        self.portfolioInformationField = portfolioInformationField
        self.priorityField = priorityField
        self.sLAField = sLAField
        self.sendFirstEmailField = sendFirstEmailField
        self.sendWorkflowEmailsField = sendWorkflowEmailsField
        self.tokenField = tokenField
        self.workflowUsersListField = workflowUsersListField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case additionalDataField = "AdditionalDataField"
        case autoRemindField = "AutoRemindField"
        case customMessageField = "CustomMessageField"
        case docField = "DocField"
        case docNameField = "DocNameField"
        case dueDateField = "DueDateField"
        case extensionField = "ExtensionField"
        case flattenDocumentField = "FlattenDocumentField"
        case keepContentSecurityField = "KeepContentSecurityField"
        case keepCustomPropertiesField = "KeepCustomPropertiesField"
        case keepXMPMetadataField = "KeepXMPMetadataField"
        case portfolioInformationField = "PortfolioInformationField"
        case priorityField = "PriorityField"
        case sLAField = "SLAField"
        case sendFirstEmailField = "SendFirstEmailField"
        case sendWorkflowEmailsField = "SendWorkflowEmailsField"
        case tokenField = "TokenField"
        case workflowUsersListField = "WorkflowUsersListField"
    }

}
