//
// GetAuditDocumentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when requesting and audit document. */
public struct GetAuditDocumentResponse: Codable {

    public var auditDocumentField: String
    /** Displays the result of the call. */
    public var resultField: String

    public init(auditDocumentField: String, resultField: String) {
        self.auditDocumentField = auditDocumentField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case auditDocumentField = "AuditDocumentField"
        case resultField = "ResultField"
    }

}
