//
// GetAuditDocumentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### A request sent to get an audit document. */
public struct GetAuditDocumentRequest: Codable {

    public var docIDField: String
    public var tokenField: TokenField

    public init(docIDField: String, tokenField: TokenField) {
        self.docIDField = docIDField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case tokenField = "TokenField"
    }

}
