//
// GetDocumentAuditResponseActivityField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDocumentAuditResponseActivityField: Codable {

    public var actionOrderField: String
    public var additionalField: String
    public var docIDField: String
    /** The user&#39;s email. */
    public var emailField: String
    public var eventDateField: String
    public var eventField: String
    public var eventStatusField: String
    public var locationField: String
    public var orderDateField: String
    public var pageField: String
    /** User&#39;s full name. */
    public var userFullNameField: String

    public init(actionOrderField: String, additionalField: String, docIDField: String, emailField: String, eventDateField: String, eventField: String, eventStatusField: String, locationField: String, orderDateField: String, pageField: String, userFullNameField: String) {
        self.actionOrderField = actionOrderField
        self.additionalField = additionalField
        self.docIDField = docIDField
        self.emailField = emailField
        self.eventDateField = eventDateField
        self.eventField = eventField
        self.eventStatusField = eventStatusField
        self.locationField = locationField
        self.orderDateField = orderDateField
        self.pageField = pageField
        self.userFullNameField = userFullNameField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionOrderField = "ActionOrderField"
        case additionalField = "AdditionalField"
        case docIDField = "DocIDField"
        case emailField = "EmailField"
        case eventDateField = "EventDateField"
        case eventField = "EventField"
        case eventStatusField = "EventStatusField"
        case locationField = "LocationField"
        case orderDateField = "OrderDateField"
        case pageField = "PageField"
        case userFullNameField = "UserFullNameField"
    }

}
