//
// GetDocStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response returned when a document status has been requested. */
public struct GetDocStatusResponse: Codable {

    /** Status of the document. */
    public var docStatusField: String
    /** Displays the result of the call. */
    public var resultField: String

    public init(docStatusField: String, resultField: String) {
        self.docStatusField = docStatusField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docStatusField = "DocStatusField"
        case resultField = "ResultField"
    }

}
