//
// GetDocumentTagFieldBoxPositionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned after requesting the document tag field ox position. */
public struct GetDocumentTagFieldBoxPositionResponse: Codable {

    public var documentTagFieldsBoxPositionField: GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField
    /** Displays the result of the call. */
    public var resultField: String

    public init(documentTagFieldsBoxPositionField: GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField, resultField: String) {
        self.documentTagFieldsBoxPositionField = documentTagFieldsBoxPositionField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentTagFieldsBoxPositionField = "DocumentTagFieldsBoxPositionField"
        case resultField = "ResultField"
    }

}
