//
// GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField: Codable {

    /** The page number where the field is. */
    public var pageNumberField: Double
    /** The y coordinates of the field. */
    public var xCoordinateField: String
    /** The x coordinates of the field. */
    public var yCoordinateField: String

    public init(pageNumberField: Double, xCoordinateField: String, yCoordinateField: String) {
        self.pageNumberField = pageNumberField
        self.xCoordinateField = xCoordinateField
        self.yCoordinateField = yCoordinateField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pageNumberField = "PageNumberField"
        case xCoordinateField = "XCoordinateField"
        case yCoordinateField = "YCoordinateField"
    }

}
