//
// GetDocumentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent when a user wants to download a document. */
public struct GetDocumentRequest: Codable {

    /** Document ID generated by SigniFlow. */
    public var docIDField: Double
    public var tokenField: TokenField

    public init(docIDField: Double, tokenField: TokenField) {
        self.docIDField = docIDField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case tokenField = "TokenField"
    }

}
