//
// GetDocumentAuditResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned after requesting the audit information from a document. */
public struct GetDocumentAuditResponse: Codable {

    public var activityField: Set<GetDocumentAuditResponseActivityField>
    /** Displays the result of the call. */
    public var resultField: String

    public init(activityField: Set<GetDocumentAuditResponseActivityField>, resultField: String) {
        self.activityField = activityField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activityField = "ActivityField"
        case resultField = "ResultField"
    }

}
