//
// GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField: Codable {

    /** The height of the field. */
    public var heightField: String
    /** The page number where the field is. */
    public var pageNumberField: Double
    public var widthField: String
    /** The x coordinates of the field. */
    public var xCoordinateField: String
    /** The y coordinates of the field */
    public var yCoordinateField: String

    public init(heightField: String, pageNumberField: Double, widthField: String, xCoordinateField: String, yCoordinateField: String) {
        self.heightField = heightField
        self.pageNumberField = pageNumberField
        self.widthField = widthField
        self.xCoordinateField = xCoordinateField
        self.yCoordinateField = yCoordinateField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case heightField = "HeightField"
        case pageNumberField = "PageNumberField"
        case widthField = "WidthField"
        case xCoordinateField = "XCoordinateField"
        case yCoordinateField = "YCoordinateField"
    }

}
