//
// GetDocumentTagFieldPositionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when requesting the document tag field position. */
public struct GetDocumentTagFieldPositionResponse: Codable {

    public var documentTagFieldsPositionField: Set<GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField>
    /** Displays the result of the call. */
    public var resultField: String

    public init(documentTagFieldsPositionField: Set<GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField>, resultField: String) {
        self.documentTagFieldsPositionField = documentTagFieldsPositionField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentTagFieldsPositionField = "DocumentTagFieldsPositionField"
        case resultField = "ResultField"
    }

}
