//
// GetDocumentTagFieldPositionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent to get the document tag field position. */
public struct GetDocumentTagFieldPositionRequest: Codable {

    public var docIDField: Double
    public var tagNameField: String
    public var tokenField: TokenField

    public init(docIDField: Double, tagNameField: String, tokenField: TokenField) {
        self.docIDField = docIDField
        self.tagNameField = tagNameField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case tagNameField = "TagNameField"
        case tokenField = "TokenField"
    }

}
