//
// GetDocumentPrepperLinkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the request sent to get a documnt prepper url. */
public struct GetDocumentPrepperLinkRequest: Codable {

    public var docIDField: String
    public var emailSettingField: Double
    public var returnURLField: String
    public var tokenField: TokenField

    public init(docIDField: String, emailSettingField: Double, returnURLField: String, tokenField: TokenField) {
        self.docIDField = docIDField
        self.emailSettingField = emailSettingField
        self.returnURLField = returnURLField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case emailSettingField = "EmailSettingField"
        case returnURLField = "ReturnURLField"
        case tokenField = "TokenField"
    }

}
