//
// GetDocumentPrepperLinkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response returned when requesting a document prepper url. */
public struct GetDocumentPrepperLinkResponse: Codable {

    /** Displays the result of the call. */
    public var result: String
    /** Url */
    public var URL: String

    public init(result: String, URL: String) {
        self.result = result
        self.URL = URL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case result = "Result"
        case URL
    }

}
