//
// GetDocLinkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response returned when a document url is requested. */
public struct GetDocLinkResponse: Codable {

    /** Displays the result of the call. */
    public var result: String
    /** URL */
    public var url: String

    public init(result: String, url: String) {
        self.result = result
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case result = "Result"
        case url = "Url"
    }

}
