//
// GetPrepperTemplateListResponseTemplateInformationValuesField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPrepperTemplateListResponseTemplateInformationValuesField: Codable {

    public var nameField: String
    public var prepperTemplateIDField: Double
    /** Template description. */
    public var templateDescriptionField: String

    public init(nameField: String, prepperTemplateIDField: Double, templateDescriptionField: String) {
        self.nameField = nameField
        self.prepperTemplateIDField = prepperTemplateIDField
        self.templateDescriptionField = templateDescriptionField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nameField = "NameField"
        case prepperTemplateIDField = "PrepperTemplateIDField"
        case templateDescriptionField = "TemplateDescriptionField"
    }

}
