//
// GetPrepperTemplateResponsePrepperTemplateValuesField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPrepperTemplateResponsePrepperTemplateValuesField: Codable {

    public var colorField: String
    public var docFieldIDField: String
    public var docIDField: Double
    public var fieldTypeField: String
    /** Field height. */
    public var heightField: Double
    public var pageNumberField: Double
    /** The user&#39;s full name. */
    public var userFullNameField: String
    /** The user&#39;s ID. */
    public var userIDField: Double
    public var valueField: String
    /** Field width. */
    public var widthField: Double
    /** The x coordinates of the fields. */
    public var xCoordinateField: Double
    /** The y coordinates of the fields */
    public var yCoordinateField: Double

    public init(colorField: String, docFieldIDField: String, docIDField: Double, fieldTypeField: String, heightField: Double, pageNumberField: Double, userFullNameField: String, userIDField: Double, valueField: String, widthField: Double, xCoordinateField: Double, yCoordinateField: Double) {
        self.colorField = colorField
        self.docFieldIDField = docFieldIDField
        self.docIDField = docIDField
        self.fieldTypeField = fieldTypeField
        self.heightField = heightField
        self.pageNumberField = pageNumberField
        self.userFullNameField = userFullNameField
        self.userIDField = userIDField
        self.valueField = valueField
        self.widthField = widthField
        self.xCoordinateField = xCoordinateField
        self.yCoordinateField = yCoordinateField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case colorField = "ColorField"
        case docFieldIDField = "DocFieldIDField"
        case docIDField = "DocIDField"
        case fieldTypeField = "FieldTypeField"
        case heightField = "HeightField"
        case pageNumberField = "PageNumberField"
        case userFullNameField = "UserFullNameField"
        case userIDField = "UserIDField"
        case valueField = "ValueField"
        case widthField = "WidthField"
        case xCoordinateField = "XCoordinateField"
        case yCoordinateField = "YCoordinateField"
    }

}
