//
// GetPrepperTemplateListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent to get the document template list. */
public struct GetPrepperTemplateListRequest: Codable {

    public var templateFolderField: Double
    public var tokenField: TokenField

    public init(templateFolderField: Double, tokenField: TokenField) {
        self.templateFolderField = templateFolderField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templateFolderField = "TemplateFolderField"
        case tokenField = "TokenField"
    }

}
