//
// InitiateFlowNoInitialEmailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent to initiate a workflow skiiping the first email. */
public struct InitiateFlowNoInitialEmailRequest: Codable {

    /** The document ID. */
    public var docIDField: String
    public var tokenField: TokenField

    public init(docIDField: String, tokenField: TokenField) {
        self.docIDField = docIDField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case tokenField = "TokenField"
    }

}
