//
// InitiateFlowNoEmailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when a workflow is requested without any email. */
public struct InitiateFlowNoEmailResponse: Codable {

    /** The document ID. */
    public var docIDField: Double
    /** Displays the result of the call. */
    public var resultField: String

    public init(docIDField: Double, resultField: String) {
        self.docIDField = docIDField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case resultField = "ResultField"
    }

}
