//
// LinkToPortfolioRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This request is used to get the url link to a portfolio. */
public struct LinkToPortfolioRequest: Codable {

    /** The document ID. */
    public var docIDField: String
    /** Document name. */
    public var documentNameField: String
    /** The portfolio ID. */
    public var portfolioIDField: String
    public var tokenField: TokenField

    public init(docIDField: String, documentNameField: String, portfolioIDField: String, tokenField: TokenField) {
        self.docIDField = docIDField
        self.documentNameField = documentNameField
        self.portfolioIDField = portfolioIDField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case documentNameField = "DocumentNameField"
        case portfolioIDField = "PortfolioIDField"
        case tokenField = "TokenField"
    }

}
