//
// LinkToPortfolioResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response returned after requesting a url link to a portfolio. */
public struct LinkToPortfolioResponse: Codable {

    /** The portfolio ID. */
    public var portfolioIDField: String
    /** Displays the result of the call. */
    public var resultField: String

    public init(portfolioIDField: String, resultField: String) {
        self.portfolioIDField = portfolioIDField
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case portfolioIDField = "PortfolioIDField"
        case resultField = "ResultField"
    }

}
