//
// LoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent when a user Logs in. */
public struct LoginRequest: Codable {

    /** Email address of the user generating a Token */
    public var userNameField: String
    /** SigniFlow user password */
    public var passwordField: String

    public init(userNameField: String, passwordField: String) {
        self.userNameField = userNameField
        self.passwordField = passwordField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userNameField = "UserNameField"
        case passwordField = "PasswordField"
    }

}
