//
// LogoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent when a user logs out. */
public struct LogoutRequest: Codable {

    public var tokenField: String

    public init(tokenField: String) {
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenField = "TokenField"
    }

}
