//
// MultipleSignersSigningCeremonyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the request sent when there are multiple signers on a document. */
public struct MultipleSignersSigningCeremonyRequest: Codable {

    public var docField: String
    public var docNameField: String
    /** User&#39;s password. */
    public var loginPasswordField: String
    /** User&#39;s username. */
    public var loginUserNameField: String
    public var signerListField: Set<MultipleSignersSigningCeremonyRequestSignerListField>

    public init(docField: String, docNameField: String, loginPasswordField: String, loginUserNameField: String, signerListField: Set<MultipleSignersSigningCeremonyRequestSignerListField>) {
        self.docField = docField
        self.docNameField = docNameField
        self.loginPasswordField = loginPasswordField
        self.loginUserNameField = loginUserNameField
        self.signerListField = signerListField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docField = "DocField"
        case docNameField = "DocNameField"
        case loginPasswordField = "LoginPasswordField"
        case loginUserNameField = "LoginUserNameField"
        case signerListField = "SignerListField"
    }

}
