//
// Priority.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The priority level of the workflow.   &#x60;0 &#x3D; Low 1 &#x3D; Normal 2 &#x3D; High&#x60; */
public enum Priority: Int, Codable, CaseIterable {
    case Low = 0
    case Normal = 1
    case High = 2
}
