//
// SetDocumentOrderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent when the document order for signing is confirmed. */
public struct SetDocumentOrderRequest: Codable {

    public var docIDField: String
    public var documentOrderField: String
    public var tokenField: TokenField

    public init(docIDField: String, documentOrderField: String, tokenField: TokenField) {
        self.docIDField = docIDField
        self.documentOrderField = documentOrderField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case documentOrderField = "DocumentOrderField"
        case tokenField = "TokenField"
    }

}
