//
// SetDocumentOrderResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when the document order for signing is set. */
public struct SetDocumentOrderResponse: Codable {

    /** Displays the result of the call. */
    public var resultField: String

    public init(resultField: String) {
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resultField = "ResultField"
    }

}
