//
// SharePortfolioResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when a user wants to share a portfolio. */
public struct SharePortfolioResponse: Codable {

    /** Displays the result of the call. */
    public var resultField: String

    public init(resultField: String) {
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resultField = "ResultField"
    }

}
