//
// SharePortfolioRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent when a user wants to share a portfolio with someone. */
public struct SharePortfolioRequest: Codable {

    public var accessLevelField: Double
    public var portfolioIDField: String
    public var shareOptionField: Double
    public var tokenField: TokenField
    public var uniqueIDField: String

    public init(accessLevelField: Double, portfolioIDField: String, shareOptionField: Double, tokenField: TokenField, uniqueIDField: String) {
        self.accessLevelField = accessLevelField
        self.portfolioIDField = portfolioIDField
        self.shareOptionField = shareOptionField
        self.tokenField = tokenField
        self.uniqueIDField = uniqueIDField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessLevelField = "AccessLevelField"
        case portfolioIDField = "PortfolioIDField"
        case shareOptionField = "ShareOptionField"
        case tokenField = "TokenField"
        case uniqueIDField = "UniqueIDField"
    }

}
