//
// SigningCeremonyV2Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The response returned when the signing process is requested. */
public struct SigningCeremonyV2Response: Codable {

    public var ceremonyIDField: Double
    /** Displays the result of the call. */
    public var resultField: String
    public var signedDocumentField: String

    public init(ceremonyIDField: Double, resultField: String, signedDocumentField: String) {
        self.ceremonyIDField = ceremonyIDField
        self.resultField = resultField
        self.signedDocumentField = signedDocumentField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ceremonyIDField = "CeremonyIDField"
        case resultField = "ResultField"
        case signedDocumentField = "SignedDocumentField"
    }

}
