//
// TokenExtendRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### The request sent to extend the session time by extending the period when the token is valid. */
public struct TokenExtendRequest: Codable {

    public var tokenField: TokenField
    public var tokenValidityField: Double

    public init(tokenField: TokenField, tokenValidityField: Double) {
        self.tokenField = tokenField
        self.tokenValidityField = tokenValidityField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenField = "TokenField"
        case tokenValidityField = "TokenValidityField"
    }

}
