//
// TokenField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### Authentication Token */
public struct TokenField: Codable {

    /** Expiry date of Token */
    public var tokenExpiryField: Date?
    /** User API Token */
    public var tokenField: String

    public init(tokenExpiryField: Date? = nil, tokenField: String) {
        self.tokenExpiryField = tokenExpiryField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenExpiryField = "TokenExpiryField"
        case tokenField = "TokenField"
    }

}
