//
// WorkflowSignRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This request is sent when a document workflow needs to be signed. */
public struct WorkflowSignRequest: Codable {

    public var docIDField: String
    public var latitudeField: String
    public var loginPasswordField: String
    public var loginUserNameField: String
    public var longitudeField: String
    public var signReasonField: String
    public var timeZoneOffsetField: Double
    public var tokenField: TokenField

    public init(docIDField: String, latitudeField: String, loginPasswordField: String, loginUserNameField: String, longitudeField: String, signReasonField: String, timeZoneOffsetField: Double, tokenField: TokenField) {
        self.docIDField = docIDField
        self.latitudeField = latitudeField
        self.loginPasswordField = loginPasswordField
        self.loginUserNameField = loginUserNameField
        self.longitudeField = longitudeField
        self.signReasonField = signReasonField
        self.timeZoneOffsetField = timeZoneOffsetField
        self.tokenField = tokenField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docIDField = "DocIDField"
        case latitudeField = "LatitudeField"
        case loginPasswordField = "LoginPasswordField"
        case loginUserNameField = "LoginUserNameField"
        case longitudeField = "LongitudeField"
        case signReasonField = "SignReasonField"
        case timeZoneOffsetField = "TimeZoneOffsetField"
        case tokenField = "TokenField"
    }

}
