//
// WorkflowSignResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** #### This is the response returned when a user gets a request to sign a document workflow. */
public struct WorkflowSignResponse: Codable {

    /** Displays the result of the call. */
    public var resultField: String

    public init(resultField: String) {
        self.resultField = resultField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resultField = "ResultField"
    }

}
